apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/sonyali03/sonyademo-go36:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/sonyali03/sonyademo-go36:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: sonyademo-go36
        chartPath: charts/sonyademo-go36
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/sonyali03/sonyademo-go36'
          image.tag: '{{.DIGEST_HEX}}'
